from __future__ import annotations

import argparse
import json
from pathlib import Path

from ultralytics import YOLO

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DATA = ROOT / "datasets" / "road_damage" / "data.yaml"
REPORT_DIR = ROOT / "reports"


def evaluate(weights: str, data: str | None = None, split: str = "test", imgsz: int = 640) -> dict:
    data_path = Path(data) if data else DEFAULT_DATA
    if not data_path.exists():
        raise FileNotFoundError(f"Dataset config missing: {data_path}")
    if not Path(weights).exists():
        raise FileNotFoundError(f"Weights missing: {weights}")

    model = YOLO(weights)
    metrics = model.val(data=str(data_path), split=split, imgsz=imgsz, plots=True)

    box = metrics.box
    report = {
        "weights": str(Path(weights).resolve()),
        "dataset": str(data_path.resolve()),
        "split": split,
        "imgsz": imgsz,
        "precision": float(box.mp),
        "recall": float(box.mr),
        "map50": float(box.map50),
        "map50_95": float(box.map),
        "class_names": metrics.names,
        "note": "Metrics are generated by Ultralytics validation on the configured dataset split; do not reuse for another dataset/model.",
    }

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    output = REPORT_DIR / "road_damage_metrics.json"
    output.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))
    print(f"Saved report: {output}")
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--weights", required=True)
    parser.add_argument("--data", default=None)
    parser.add_argument("--split", default="test", choices=["val", "test"])
    parser.add_argument("--imgsz", type=int, default=640)
    args = parser.parse_args()
    evaluate(args.weights, args.data, args.split, args.imgsz)


if __name__ == "__main__":
    main()
